export interface SchemaVersion {
  version: string;
  requiredTables: string[];
  requiredColumns: Record<string, string[]>;
  optionalColumns: Record<string, string[]>;
  migrationStatus: 'complete' | 'in-progress' | 'pending';
  notes?: string;
}

export const SCHEMA_VERSIONS: Record<string, SchemaVersion> = {
  '2.13.29': {
    version: '2.13.29',
    requiredTables: [
      'events',
      'JournalSections', 
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'images',
        'status',
        'tags',
        'user_id',
        'published_at',
        'created_at',
        'updated_at'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'caption',
        'description',
        'taken_date',
        'photo_type',
        'file_data',
        'file_size',
        'mime_type',
        's3_url',
        'created_at',
        'updated_at'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'title',
        'description',
        'category',
        'difficulty_level',
        'prep_time',
        'cook_time',
        'servings',
        'is_featured',
        'image_filename',
        'image_s3_url',
        'user_id',
        'ingredients',
        'instructions',
        'created_at',
        'updated_at'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ]
    },
    optionalColumns: {
      'JournalContentItems': [
        'manual_page_break',
        'page_break_position'
      ]
    },
    migrationStatus: 'complete',
    notes: 'Initial schema verification system - JournalPages renamed to JournalSections'
  },
  '2.13.30': {
    version: '2.13.30',
    requiredTables: [
      'events',
      'JournalSections', 
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'role',
        'first_name',
        'last_name',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Added manual_page_break and page_break_position columns to JournalContentItems as required fields'
  },
  '3.0.0': {
    version: '3.0.0',
    requiredTables: [
      'events',
      'JournalSections', 
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'ScrapbookFiles'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'is_published',
        'layout_config',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'role',
        'first_name',
        'last_name',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'ScrapbookFiles': [
        'id',
        'year',
        'filename',
        'local_path',
        's3_url',
        's3_key',
        'status',
        'file_size',
        'generated_at',
        'last_accessed',
        'access_count',
        'error_message',
        'created_at',
        'updated_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Major release: Added ScrapbookContent and ScrapbookFiles tables for scrapbook generation system. Added is_published field to JournalSections. Complete scrapbook viewer system with year selection interface.'
  },
  '3.0.1': {
    version: '3.0.1',
    requiredTables: [
      'events',
      'JournalSections',
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'ScrapbookFiles'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'is_published',
        'layout_config',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'display_order',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'first_name',
        'last_name',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'ScrapbookFiles': [
        'id',
        'year',
        'filename',
        'local_path',
        's3_url',
        's3_key',
        'status',
        'file_size',
        'generated_at',
        'last_accessed',
        'access_count',
        'error_message',
        'created_at',
        'updated_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Patch release: Fixed TypeScript errors in scrapbookRoutes by adding explicit return statements to all route handlers and fixing unused parameter warnings. No database schema changes.'
  },
  '3.1.2': {
    version: '3.1.2',
    requiredTables: [
      'events',
      'JournalSections',
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'ScrapbookFiles',
      'PasswordResetTokens'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'is_published',
        'layout_config',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'first_name',
        'last_name',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'ScrapbookFiles': [
        'id',
        'year',
        'filename',
        'local_path',
        's3_url',
        's3_key',
        'status',
        'file_size',
        'generated_at',
        'last_accessed',
        'access_count',
        'error_message',
        'created_at',
        'updated_at'
      ],
      'PasswordResetTokens': [
        'id',
        'user_id',
        'token',
        'expires_at',
        'used',
        'created_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Feature release: Added password reset and forgot credentials functionality. Added PasswordResetTokens table for secure password reset tokens. Integrated Mailgun email service for sending password reset and username recovery emails.'
  },
  '3.1.3': {
    version: '3.1.3',
    requiredTables: [
      'events',
      'JournalSections',
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'ScrapbookFiles',
      'PasswordResetTokens'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'is_published',
        'layout_config',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'first_name',
        'last_name',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'ScrapbookFiles': [
        'id',
        'year',
        'filename',
        'local_path',
        's3_url',
        's3_key',
        'status',
        'file_size',
        'generated_at',
        'last_accessed',
        'access_count',
        'error_message',
        'created_at',
        'updated_at'
      ],
      'PasswordResetTokens': [
        'id',
        'user_id',
        'token',
        'expires_at',
        'used',
        'created_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Security release: Removed hardcoded Mailgun API key from email service. Now uses environment variables exclusively with proper validation. Same functionality, improved security.'
  },
  '3.1.5': {
    version: '3.1.5',
    requiredTables: [
      'events',
      'JournalSections',
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'ScrapbookFiles',
      'PasswordResetTokens'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'is_published',
        'layout_config',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'first_name',
        'last_name',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'ScrapbookFiles': [
        'id',
        'year',
        'filename',
        'local_path',
        's3_url',
        's3_key',
        'status',
        'file_size',
        'generated_at',
        'last_accessed',
        'access_count',
        'error_message',
        'created_at',
        'updated_at'
      ],
      'PasswordResetTokens': [
        'id',
        'user_id',
        'token',
        'expires_at',
        'used',
        'created_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Bug fix release: Fixed TypeScript compilation errors in emailService.ts by removing unused imports and variables. No database schema changes.'
  },
  '3.1.6': {
    version: '3.1.6',
    requiredTables: [
      'events',
      'JournalSections',
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'ScrapbookFiles',
      'PasswordResetTokens'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'is_published',
        'layout_config',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'first_name',
        'last_name',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'ScrapbookFiles': [
        'id',
        'year',
        'filename',
        'local_path',
        's3_url',
        's3_key',
        'status',
        'file_size',
        'generated_at',
        'last_accessed',
        'access_count',
        'error_message',
        'created_at',
        'updated_at'
      ],
      'PasswordResetTokens': [
        'id',
        'user_id',
        'token',
        'expires_at',
        'used',
        'created_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Production fix release: Fixed Railway deployment healthcheck failure by suppressing express-session MemoryStore warnings in production environment. No database schema changes.'
  },
  '3.1.7': {
    version: '3.1.7',
    requiredTables: [
      'events',
      'JournalSections',
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'ScrapbookFiles',
      'PasswordResetTokens'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name', 
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'is_published',
        'layout_config',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'first_name',
        'last_name',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'ScrapbookFiles': [
        'id',
        'year',
        'filename',
        'local_path',
        's3_url',
        's3_key',
        'status',
        'file_size',
        'generated_at',
        'last_accessed',
        'access_count',
        'error_message',
        'created_at',
        'updated_at'
      ],
      'PasswordResetTokens': [
        'id',
        'user_id',
        'token',
        'expires_at',
        'used',
        'created_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Production fix release: Improved MemoryStore warning suppression by redirecting stderr instead of console.warn. This should resolve Railway healthcheck failures caused by express-session MemoryStore warnings. No database schema changes.'
  },
  '3.1.8': {
    version: '3.1.8',
    requiredTables: [
      'events',
      'JournalSections',
      'JournalContentItems',
      'Users',
      'BlogPosts',
      'Photos',
      'Recipes',
      'Sessions',
      'ScrapbookContent',
      'PasswordResetTokens'
    ],
    requiredColumns: {
      'events': [
        'event_id',
        'event_name',
        'event_type',
        'event_location',
        'event_date',
        'event_description',
        'menu_title',
        'menu_image_filename',
        'created_at',
        'updated_at',
        'menu_image_s3_url'
      ],
      'JournalSections': [
        'section_id',
        'event_id',
        'year',
        'section_order',
        'title',
        'description',
        'layout_config',
        'is_published',
        'created_at',
        'updated_at'
      ],
      'JournalContentItems': [
        'content_item_id',
        'journal_section_id',
        'content_type',
        'content_id',
        'custom_text',
        'heading_level',
        'display_order',
        'is_visible',
        'manual_page_break',
        'page_break_position',
        'created_at',
        'updated_at'
      ],
      'Users': [
        'user_id',
        'username',
        'email',
        'password_hash',
        'first_name',
        'last_name',
        'role',
        'created_at',
        'updated_at'
      ],
      'BlogPosts': [
        'blog_post_id',
        'event_id',
        'user_id',
        'title',
        'content',
        'excerpt',
        'featured_image',
        'tags',
        'status',
        'published_at',
        'created_at',
        'updated_at',
        'images'
      ],
      'Photos': [
        'photo_id',
        'event_id',
        'filename',
        'original_filename',
        'description',
        'caption',
        'taken_date',
        'file_size',
        'mime_type',
        'file_data',
        'created_at',
        'updated_at',
        's3_url',
        'photo_type'
      ],
      'Recipes': [
        'recipe_id',
        'event_id',
        'user_id',
        'title',
        'description',
        'ingredients',
        'instructions',
        'prep_time',
        'cook_time',
        'servings',
        'difficulty_level',
        'category',
        'image_filename',
        'is_featured',
        'created_at',
        'updated_at',
        'image_s3_url'
      ],
      'Sessions': [
        'session_id',
        'user_id',
        'expires',
        'data',
        'created_at'
      ],
      'ScrapbookContent': [
        'id',
        'year',
        'content_type',
        'content_reference',
        'display_order',
        'page_break_before',
        'page_break_after',
        'created_at'
      ],
      'PasswordResetTokens': [
        'id',
        'user_id',
        'token',
        'expires_at',
        'used',
        'created_at'
      ]
    },
    optionalColumns: {},
    migrationStatus: 'complete',
    notes: 'Enhanced debugging release: Added comprehensive step-by-step logging to password reset route to trace exactly where the process fails. Includes detailed error logging with stack traces. No database schema changes.'
  }
};

export const getCurrentVersion = (): string => {
  try {
    const packageJson = require('../../package.json');
    return packageJson.version;
  } catch (error) {
    console.error('Failed to get current version from package.json:', error);
    return 'unknown';
  }
};

export const getSchemaVersion = (version: string): SchemaVersion | null => {
  return SCHEMA_VERSIONS[version] || null;
};

export const hasSchemaDefinition = (version: string): boolean => {
  return version in SCHEMA_VERSIONS;
};

export const getLatestSchemaVersion = (): string => {
  const versions = Object.keys(SCHEMA_VERSIONS).sort((a, b) => {
    // Simple version comparison - could be improved with semver
    return a.localeCompare(b, undefined, { numeric: true });
  });
  return versions[versions.length - 1] || 'unknown';
};
