name: Enforce Branch Promotion Order

on:
  pull_request:
    branches:
      - main
      - test

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"

          if [[ "$GITHUB_BASE_REF" == "test" && "$GITHUB_HEAD_REF" != "dev" ]]; then
            echo "❌ Only 'dev' can merge into 'test'. Found: $GITHUB_HEAD_REF"
            exit 1
          fi

          if [[ "$GITHUB_BASE_REF" == "main" && "$GITHUB_HEAD_REF" != "test" ]]; then
            echo "❌ Only 'test' can merge into 'main'. Found: $GITHUB_HEAD_REF"
            exit 1
          fi

          echo "✅ Branch promotion order is valid"
